// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ESPWatchFace

#include "../ui.h"

void ui_WatchScreen_screen_init(void)
{
ui_WatchScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WatchScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WatchScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WatchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DialFace = lv_img_create(ui_WatchScreen);
lv_img_set_src(ui_DialFace, &ui_img_dial_face_png);
lv_obj_set_width( ui_DialFace, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_DialFace, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_DialFace, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DialFace, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DialFace, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HourHand = lv_img_create(ui_WatchScreen);
lv_img_set_src(ui_HourHand, &ui_img_hour_hand_png);
lv_obj_set_width( ui_HourHand, LV_SIZE_CONTENT);  /// 14
lv_obj_set_height( ui_HourHand, LV_SIZE_CONTENT);   /// 54
lv_obj_set_x( ui_HourHand, 0 );
lv_obj_set_y( ui_HourHand, -20 );
lv_obj_set_align( ui_HourHand, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HourHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HourHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_HourHand,7,48);
lv_img_set_angle(ui_HourHand,1);

ui_MinuteHand = lv_img_create(ui_WatchScreen);
lv_img_set_src(ui_MinuteHand, &ui_img_minute_hand_png);
lv_obj_set_width( ui_MinuteHand, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_MinuteHand, LV_SIZE_CONTENT);   /// 69
lv_obj_set_x( ui_MinuteHand, 0 );
lv_obj_set_y( ui_MinuteHand, -30 );
lv_obj_set_align( ui_MinuteHand, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MinuteHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MinuteHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_MinuteHand,5,63);

ui_SecondHand = lv_img_create(ui_WatchScreen);
lv_img_set_src(ui_SecondHand, &ui_img_second_hand_png);
lv_obj_set_width( ui_SecondHand, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_SecondHand, LV_SIZE_CONTENT);   /// 87
lv_obj_set_x( ui_SecondHand, 0 );
lv_obj_set_y( ui_SecondHand, -39 );
lv_obj_set_align( ui_SecondHand, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SecondHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SecondHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_SecondHand,5,82);

ui_SystemStats = lv_label_create(ui_WatchScreen);
lv_obj_set_width( ui_SystemStats, 100);
lv_obj_set_height( ui_SystemStats, 50);
lv_obj_set_x( ui_SystemStats, 0 );
lv_obj_set_y( ui_SystemStats, 36 );
lv_obj_set_align( ui_SystemStats, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemStats,"");
lv_obj_set_style_text_align(ui_SystemStats, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChargingIndicator = lv_obj_create(ui_WatchScreen);
lv_obj_set_width( ui_ChargingIndicator, 20);
lv_obj_set_height( ui_ChargingIndicator, 20);
lv_obj_set_x( ui_ChargingIndicator, 100 );
lv_obj_set_y( ui_ChargingIndicator, -100 );
lv_obj_set_align( ui_ChargingIndicator, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ChargingIndicator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ChargingIndicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChargingIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ChargingIndicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChargingIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
