// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ESPWatchFace

#ifndef _ESPWATCHFACE_UI_H
#define _ESPWATCHFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_WatchScreen
void ui_WatchScreen_screen_init(void);
extern lv_obj_t *ui_WatchScreen;
extern lv_obj_t *ui_DialFace;
extern lv_obj_t *ui_HourHand;
extern lv_obj_t *ui_MinuteHand;
extern lv_obj_t *ui_SecondHand;
extern lv_obj_t *ui_SystemStats;
extern lv_obj_t *ui_ChargingIndicator;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_dial_face_png);   // assets/Dial Face.png
LV_IMG_DECLARE( ui_img_hour_hand_png);   // assets/Hour Hand.png
LV_IMG_DECLARE( ui_img_minute_hand_png);   // assets/Minute Hand.png
LV_IMG_DECLARE( ui_img_second_hand_png);   // assets/Second Hand.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
