M48
; DRILL file {KiCad 7.0.2-0} date 2023 July 19, Wednesday 09:37:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-19T09:37:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X32.105Y-34.61
X32.105Y-40.39
T2
X32.569Y-24.33
X33.585Y-29.41
X34.601Y-24.33
T3
X32.7Y-55.5
X44.0Y-19.5
X55.3Y-55.5
T0
M30
